const avCarList = [
  {
    id: 1,
    title: "clio4",
    category: "cat1",
    price: 29,
    img: "./Car_imges/clio4.png",
    desc: `Performed suspicion in certainty so frankness by attention pretended. Newspaper or in`,
  },
  {
    id: 2,
    title: "dokker",
    category: "cat3",
    price: 29,
    img: "./Car_imges/dokker.png",
    desc: `Living valley had silent eat merits esteem bed. In last an or went wise as left. Visited civilly`,
  },
  {
    id: 3,
    title: "citroen-c3",
    category: "cat1",
    price: 29,
    img: "./Car_imges/citroen-c3.png",
    desc: `Arrival entered an if drawing request. How daughters not promotion few knowledge`,
  },
  {
    id: 4,
    title: "duster",
    category: "cat2",
    price: 29,
    img: "./Car_imges/duster.png",
    desc: `Vanity day giving points within six not law. Few impression difficulty his use has comparison decisively.`,
  },
  {
    id: 5,
    title: "fiat tipo",
    category: "cat2",
    price: 29,
    img: "./Car_imges/fiat_tipo.png",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "peugeot",
    category: "cat3",
    price: 29,
    img: "./Car_imges/peugeot.png",
    desc: `On projection apartments unsatiable so if he entreaties appearance. Rose you wife how set`,
  },
  {
    id: 7,
    title: "sandero",
    category: "cat1",
    price: 29,
    img: "./Car_imges/sandero.png",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "peugeot 208",
    category: "cat3",
    price: 29,
    img: "./Car_imges/peugeot-208.png",
    desc: `astonished on of ye. Partiality on or continuing in particular principles as. Do believing oh `,
  },
]

export default avCarList
